# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('mod_date', models.DateTimeField(verbose_name='Date last modified')),
                ('hidden', models.BooleanField(default=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
